# Generated by Django 5.2.1 on 2025-06-02 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_profile_email_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
