# Generated by Django 5.2.1 on 2025-06-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_contactmessage_responded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='⚙', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
