# Generated by Django 5.2.1 on 2025-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0011_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color1',
            field=models.CharField(default='#13141E', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='color3',
            field=models.CharField(default='#7328FF', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='color4',
            field=models.CharField(default='#28282B', max_length=50),
        ),
    ]
