# Generated by Django 5.2.1 on 2025-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0013_project_image2_project_image3_project_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
