# Generated by Django 5.2.1 on 2025-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0015_alter_project_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf',
            field=models.FileField(blank=True, upload_to='profile/'),
        ),
    ]
